### ISSUE TITLE
Quasisymmetry function specifying M/N

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#12]
@ddudt i dont know what this means

**Comment by f0uriest** [comment]
@ddudt was this resolved in the recent QS updates?

**Comment by ddudt** [comment]
Yes this was resolved with the recent updates.  I was referring to what I now call the "flux function" QS metric, but it's implemented in a way that is agnostic to specifying M/N.  The type of quasisymmetry can now be determined using booz_xform.
