### ISSUE TITLE
2nd order perturbations

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#14]
Autodiff hessian and solve quadratic tensor equation for dx
ways to format it as matrix equation?

**Comment by ddudt** [comment]
Now implemented in `dev` but might not be stable.  Boundary perturbations for both orders seem to shift the major radius outward, even with low `errr_ratio`.  Need testing to determine if there is a bug in the BC or perturbation functions.  (square system?)  
![bdry_pert_test](https://user-images.githubusercontent.com/33005725/95415626-c6812580-08fe-11eb-8216-13e8adee1090.png)

**Comment by f0uriest** [comment]
how low did you go for `errr_ratio`? I've noticed that even with pretty low values the jacobian is still dominated by a few large values in the force error, and the bc error terms are pretty small comparatively. 
We could also look into doing a weighted least squares thing (effectively using a larger error ratio just for the perturbation stuff) or regularized as well by penalizing large changes in the low mode numbers

**Comment by ddudt** [comment]
The issue was a bug in the boundary condition function.  This line: 
```
# ratio of non-axisymmetric boundary modes to use
ratio = jnp.clip(bdry_ratio+(bdryN == 0), 0, 1)
```
needed to be replaced with:
```
ratio = jnp.where(bdryN != 0, bdry_ratio, 1)
```
The performance might still be affected by the choice of `errr_ratio` weight.  
![bdry_pert_good](https://user-images.githubusercontent.com/33005725/96026483-8cdf7b80-0e24-11eb-8f7f-40369966d4a2.png)
