### ISSUE TITLE
Issue with initial guess for W7X

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#20]
This is the initial guess generated for the w7x test case. Couldn't find any obvious reason, but didn't look super close. Not sure if its an issue with the input file or the initialization function, @ddudt can you take a look? 

![image](https://user-images.githubusercontent.com/22567458/94353897-02390700-0044-11eb-91a5-2c98cfc2a2f3.png)

**Comment by f0uriest** [comment]
Similar issue for ATF but not quite as bad:

![image](https://user-images.githubusercontent.com/22567458/94353970-87242080-0044-11eb-9981-17d6799f561a.png)

**Comment by f0uriest** [comment]
and QAS:

![image](https://user-images.githubusercontent.com/22567458/94354016-eeda6b80-0044-11eb-8ca0-8630290b7985.png)

**Comment by ddudt** [comment]
![W7X_init0](https://user-images.githubusercontent.com/33005725/94728624-83d3b200-032e-11eb-9f15-9807a6581623.png)
