### ISSUE TITLE
Comments in input file not parsed if at the end of a line

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#34]
If the line begins with ``#`` or ``!``, the line is correctly parsed as a comment. But if the comment is on the same line as other stuff, it seems to get parsed as if it was all valid input
eg, ``M = 6 #6, 8, 10  `` should ideally be parsed as just ``M=6``, but it currently gets parsed as ``M=6,6,8,10``
It would be good to have it parsed the other way, both so one can quickly comment out part of a line without erasing it, and so we can have comments at the end of a line explaining what the different options do

**Comment by ddudt** [comment]
Comments are parsed correctly at the end of input file lines, as they always have been.  It still works properly for me with the functionality you stated.  Please confirm if this is actually a bug with the source code and not you accidently changing something.

**Comment by f0uriest** [comment]
ahh yep it was a bug in my end, all good
