### ISSUE TITLE
API Documentation Does Not List anything

### ISSUE THREAD

**Issue by dpanici** [ddudt/DESC#41]
Per title, after the last pull Request, the [API Documentation](https://desc-docs.readthedocs.io/en/latest/api.html) only lists headers and not any of the function, but it did before the last pull request was merged I think.

**Comment by f0uriest** [comment]
When I build it locally it seems fine, so I'm guessing it's something with readthedocs. @ddudt can you check the build log and see if anything looks weird?

**Comment by ddudt** [comment]
I can't find anything weird in the last build log.  There are a few warnings, but it looks like those warnings existed in the previous builds too.
