### ISSUE TITLE
v0.4.0 to do list

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#51]
Some stuff we should get done or look at before merging back into master. Most of it is super quick, just check them off as you do them.

## General
- [x] check how super().init works with multiple parents
- [x] test out zeta ratio
- [x] clean up documentation (no more `DESCRIPTION`, make sure everything is up to date with all the recent changes)
- [x] examples of code in use - maybe a notebook or two showing how to use it interactively

## Perturbations
- [x] optionally pass in $df/dx$
- [x] use jvp for everything else
- [x] make it a function + method of equilibrium
- [x] return new equilibrium (eq.copy())
- [x] force equilibrium to have right resolution before perturbation
- [x] def perturb(equil, objective, dx:dict, Jx=None, etc)

## Configuration
- [x] resolution for $p$, $\iota$ same as configuration
- [x] use np.where(x==[l,m,n]) instead of logical_and.reduce (see old transform.change_resolution)
- [x] make configuration ABC, not public
- [x] in config, change_resolution also changes profiles/bdry resolution
- [x] remove setter methods for basis in config
-
## Equilibrium / EquilibriumFamily
- [x] force equilibrium to have right resolution before perturbation
- [x] equil family only accepts equil as list members

## BoundaryConditions
- [x] add `build` method to BC to delay expensive SVD of A until we need it

- ## Backend/Utils
- [x] remove cross function, just import directly from jax
- [x] find better jax replacement for dot
- [x] replace tristate with `'cos'`/`'sin'`/`None`

## Objective
- [x] objective knows which transforms it needs, equilibrium gets info when objective assigned
- [x] objective has attribute for string form of its name
- [x] objectivefactory should be a function, not a class
- [x] objective has other system derivatives (df/dc stuff for each c)
- [x] objective function for minimizing energy
- [x] objective function for QS (time permitting)

## Grid
- [x] quadrature node options for radial coordinate
- [x] quadrature grid option for full quadrature setup
- [x] replace "volumes" with 1d array of weights

## Basis
- [x] numba jit where possible in basis
- [x] use np instead of jnp in building transforms
- [x] possibly extend fringe to higher L

## Transform
- [ ] better way to do fft without breaking up arrays (DCT/DST?)
- [x] figure out why fft doesnt work with symmetric basis

## IO
- [x] flag to save as vmec format
- [x] parse file name for output to figure out what format

## Plotting
- [x] logo plot function is all kinds broken
- [x] tests for plotting: http://www.davidketcheson.info/2015/01/13/using_matplotlib_image_comparison.html

**Comment by f0uriest** [comment]
@ddudt I did some profiling of the equilibrium init stuff. for w7x the whole thing takes like 15s which feels pretty long. About 9s is doing the SVD of the boundary matrix which we can add an option to wait on that till needed.
The next most expensive thing is formatting the boundary and creating the initial guess (5s total). It looks like we can probably vectorize a lot of it if we want

<script src="https://gist.github.com/f0uriest/b464aab5d2e8138cc2f5d104d15a7061.js"></script>

**Comment by ddudt** [comment]
Re: the first concern about super().init

For a class structure with multiple inheritances, Python will check the parents in the order they are listed.  In the following example, the Child constructor will call the constructor of Parent1: 
```
class Child(Parent1, Parent2):
    def __init__(self):
        super().__init__()
````
If `Parent1` does not have the desired method, then it will check `Parent2`.  Then it would check the parent of `Parent1`, then the parent of `Parent2`, etc.

So we just need to make sure that we list "primary" parents first, and other parents like `IOAble` afterwards. 

Reference: [https://stackoverflow.com/questions/3277367/how-does-pythons-super-work-with-multiple-inheritance](https://stackoverflow.com/questions/3277367/how-does-pythons-super-work-with-multiple-inheritance)
