### ISSUE TITLE
h5py<3.0.0 constraint

### ISSUE THREAD

**Issue by jonathanschilling** [ddudt/DESC#66]
Hi, 

I tried to use DESC on Arch Linux, which currently has `h5py=3.2.1` and `python=3.9.3`.
DESC's [`requirements.txt`](https://github.com/ddudt/DESC/blob/master/requirements.txt) currently enforces `h5py < 3.0.0`, which fails to build on my machine.

It would be a great improvement to allow more modern version of `h5py`.

Thanks in advance,
 Jonathan

**Comment by ddudt** [comment]
Resolved by 908e59e2f67839ce91f5538a7927cf2c009c9c82.
