### ISSUE TITLE
vmec_to_desc_input

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#8]
cannot handle multi-line VMEC inputs
need to remove pres_scale from DESC input file

**Comment by ddudt** [comment]
need to add functionality so the user can pass a VMEC input file as the command line argument

**Comment by ddudt** [comment]
VMEC input files can now be passed in place of DESC input files.  It is assumed that an input file containing "&INDATA" signifies it was intended for VMEC.  
Multi-line VMEC inputs are still not supported, but it returns an error explaining the problem.
