### ISSUE TITLE
Inaccurate use of magnetic axis guess from input file

### ISSUE THREAD

**Issue by patil3** [ddudt/DESC#92]
When the magnetic axis guess is specified as a Fourier series in phi, the code fails to use it as specified. For example, for the attached input file 'input.qhs46_v1', the expected guess (red dot) and the one used by the code (yellow dot) have been plotted for comparison. I also checked if the code simply ignores the specified guess and uses the default guess (blue dot), i.e. all the m = 0 Fourier components from the specified boundary surface. But this does not seem to be the case.
![bdry2axis2 03_edited](https://user-images.githubusercontent.com/84903460/121825365-9b15be00-cc77-11eb-9b48-039bc896c6eb.png)
[input.qhs46_v1.txt](https://github.com/ddudt/DESC/files/6644864/input.qhs46_v1.txt)

The code seems to use the n = 0 coefficient from the specified magnetic axis guess in some way (but not as expected), in addition to some series coefficients that are NOT the ones specified for R0, Z0 in the input file.
The magnetic axis guess is crucial in this case because with the default guess, the scaled-with-rho guess flux surfaces are non-nested (As seen in the figure below. Also see 'disp.txt' for the command line output from the input file 'input.qhs46_noaxis.txt'). 
![bdry2noaxis](https://user-images.githubusercontent.com/84903460/121825728-96520980-cc79-11eb-924e-3d784c143de2.png)
[disp.txt](https://github.com/ddudt/DESC/files/6644878/disp.txt)
[input.qhs46_noaxis.txt](https://github.com/ddudt/DESC/files/6644879/input.qhs46_noaxis.txt)

Another issue is that whenever this happens, the code does not write the output. Even if solving without nested surfaces is not possible, it would be helpful to have access to the output to analyze the initial guess the code used.

**Comment by ddudt** [comment]
I think this issue was resolved by commit 17e081004438e146eda5f6122f703dbd108358e1 on the `qs` branch, but it hasn't been merged into `master` yet.  I'll confirm that solution and also make sure that outputs get saved even if they don't have nested surfaces.  But you can cherry-pick that commit if you need a quick fix.

**Comment by f0uriest** [comment]
Resolved as of v0.4.7, feel free to reopen if there are still problems.
